---

- hosts: all
  become: true
  tasks:

    - name: Remove Webmin
      apt:
        name: webmin
        state: absent
        purge: yes
        autoremove: yes

    - name: Remove Webmin Repo
      apt_repository:
        repo: deb [signed-by=/etc/apt/keyrings/webmin.asc] https://download.webmin.com/download/repository sarge contrib
        state: absent

    - name: Remove Webmin Keyring
      file:
        path: /etc/apt/keyrings/webmin.asc
        state: absent
