---

- hosts: all
  become: true
  tasks:

    - name: Remove Docker Packages
      apt:
        name:
          - docker-ce
          - docker-ce-cli
          - containerd.io
          - docker-compose-plugin
        state: absent
        update_cache: yes
        purge: yes
        autoremove: yes

    - name: Remove Docker Repo
      apt_repository:
        repo: deb https://download.docker.com/linux/ubuntu {{ansible_distribution_release}} stable
        state: absent

    - name: Post Removal Reboot
      reboot:
        msg: "Post Docker Removal Reboot"
        pre_reboot_delay: 5
