---

- hosts: all
  become: true
  tasks:

    - name: Remove Docker Packages
      apt:
        name:
          - docker-ce
          - docker-ce-cli
          - containerd.io
          - docker-compose-plugin
        state: absent
        purge: yes
        autoremove: yes

    - name: Remove Docker Repo
      apt_repository:
        repo: deb [signed-by=/etc/apt/keyrings/docker.asc] https://download.docker.com/linux/ubuntu {{ansible_distribution_release}} stable
        state: absent

    - name: Remove Docker GPG Key
      file:
        path: /etc/apt/keyrings/docker.asc
        state: absent

    - name: Post Removal Reboot
      reboot:
        pre_reboot_delay: 5
